#!/bin/sh


# # Get Raspberry Pi IP address
# RASPBERRY_USER=pi
# RASPBERRY_PASSWORD=raspberry

# LOCAL_NETWORK=$(nmcli device show | grep "IP4.ROUTE\[2\]" | awk '{print $4}' | head -n 1 | head -c -2)
# RASPBERRY_IP=$(sudo arp-scan $LOCAL_NETWORK | grep Raspberry | awk '{print $1;}')


# # Connect to Raspberry Pi
# ssh $RASPBERRY_USER@$RASPBERRY_IP


# # Move to home directory
# cd $HOME


# # Update Raspberry
# sudo apt udpdate
# sudo apt upgrade -y


# # Configure Raspberry
# sudo raspi-config


# # Configure locales
# sudo export LANGUAGE=en_US.UTF-8
# sudo export LANG=en_US.UTF-8
# sudo export LC_ALL=en_US.UTF-8
# sudo locale-gen en_US.UTF-8
# sudo dpkg-reconfigure locales


# # Install Git
# sudo apt install git -y
# sudo apt install git-all -y


# # Install Oh My Bash
# bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"


# # Uninstall Oh My Bash
# uninstall_oh_my_bash


# # Enable bash history only for user session
# touch .bash_history
# chmod 000 .bash_history


# # Set up acces using ssh key
# ssh-copy-id pi@${remote_host}


# Only allow ssh using ssh key
# Modify /etc/ssh/sshd_config
cat /etc/ssh/sshd_config \
	| sed 's/PasswordAuthentication yes/PasswordAuthentication no/' \
	| sed 's/#PasswordAuthentication no/PasswordAuthentication no/' \
	| sed 's/ChallengeResponseAuthentication yes/ChallengeResponseAuthentication no/' \
	| sed 's/#ChallengeResponseAuthentication no/ChallengeResponseAuthentication no/' \
	| sed 's/UsePAM yes/UsePAM no/' \
	| sed 's/#UsePAM no/UsePAM no/' \
	> sshd_config \
	&& mv sshd_config /etc/ssh/sshd_config


# # If Permission denied (publickey)
# cat /etc/ssh/sshd_config \
#	| sed 's/RSAAuthentication yes/RSAAuthentication no/' \
#	| sed 's/#RSAAuthentication no/RSAAuthentication no/' \
#	| sed 's/PubkeyAuthentication yes/PubkeyAuthentication no/' \
#	| sed 's/#PubkeyAuthentication no/PubkeyAuthentication no/' \
#	> sshd_config \
#	&& mv sshd_config /etc/ssh/sshd_config


# Restart ssh service
sudo systemctl restart ssh.service


# # Disabling wifi and bluetooth
# rfkill block bluetooth
# rfkill block wlan

# # Setting keyboard
#
