#!/bin/bash

# Install the MongoDB 4.4 GPG key
echo " ⏳ Database install"
wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add - 1> /dev/null 2> /dev/null


# Add the source location for the MongoDB packages
echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list 1> /dev/null 2> /dev/null

# Download the package details for the MongoDB packages
sudo apt-get update 1> /dev/null 2> /dev/null

# Install MongoDB
sudo apt-get install -y mongodb-org 1> /dev/null 2> /dev/null


# Ensure mongod config is picked up:
sudo systemctl daemon-reload 1> /dev/null 2> /dev/null

# Tell systemd to run mongod on reboot:
sudo systemctl enable mongod 1> /dev/null 2> /dev/null

# Start up mongod!
sudo systemctl start mongod 1> /dev/null 2> /dev/null

echo -ne "\e[1A\e[K"
echo " ✅ Database install"
