#!/bin/sh

# Configure Raspberry
sudo raspi-config

# Configure locales
sudo export LANGUAGE=en_US.UTF-8
sudo export LANG=en_US.UTF-8
sudo export LC_ALL=en_US.UTF-8
sudo locale-gen en_US.UTF-8
sudo dpkg-reconfigure locales

# Enable bash history only for user session
touch $HOME/.bash_history
chmod 000 $HOME/.bash_history

# Disable ssh login using user and password
cat /etc/ssh/sshd_config \
	| sed 's/PasswordAuthentication yes/PasswordAuthentication no/' \
	| sed 's/#PasswordAuthentication no/PasswordAuthentication no/' \
	| sed 's/ChallengeResponseAuthentication yes/ChallengeResponseAuthentication no/' \
	| sed 's/#ChallengeResponseAuthentication no/ChallengeResponseAuthentication no/' \
	| sed 's/UsePAM yes/UsePAM no/' \
	| sed 's/#UsePAM no/UsePAM no/' \
	> sshd_config \
	&& mv sshd_config /etc/ssh/sshd_config

# Restart ssh service
sudo systemctl restart ssh.service

# Disabling wifi and bluetooth
rfkill block bluetooth
rfkill block wlan

# Setting keyboard
