#!/bin/bash

# Configure locales
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
sudo locale-gen en_US.UTF-8
sudo dpkg-reconfigure locales

# Configure keyboard
cat /etc/default/keyboard \
	| sed 's/XKBLAYOUT=\"gb\"/XKBLAYOUT=\"us\"' \
	> keyboard \
	&& sudo chown root:root keyboard \
	sudo mv keyboard /etc/default/keyboard

# Limit ssh connections through firewall
sudo ufw limit 22
sudo ufw enable

# Disable ssh login through user and password
cat /etc/ssh/sshd_config \
	| sed 's/PasswordAuthentication yes/PasswordAuthentication no/' \
	| sed 's/#PasswordAuthentication no/PasswordAuthentication no/' \
	| sed 's/ChallengeResponseAuthentication yes/ChallengeResponseAuthentication no/' \
	| sed 's/#ChallengeResponseAuthentication no/ChallengeResponseAuthentication no/' \
	| sed 's/UsePAM yes/UsePAM no/' \
	| sed 's/#UsePAM no/UsePAM no/' \
	> sshd_config \
	&& sudo chown root:root sshd_config \
	&& sudo mv sshd_config /etc/ssh/sshd_config

# Restart ssh service
sudo systemctl restart ssh.service
