#!/bin/bash

# Install oh-my-bash
curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh | bash

# Configure oh-my-bash
mv $HOME/.oh-my-bash $HOME/git/github/oh-my-bash

# Set user settings and disable auto-update
# ...

# Enable bash history only for user session
touch $HOME/.bash_history
chmod 000 $HOME/.bash_history
