#!/bin/sh

# Raspberry Pi: default user and password
RASPBERRY_USER=pi
RASPBERRY_PASSWORD=raspberry

# Raspberry Pi: IP address
RASPBERRY_IP=$(sudo arp-scan -l | grep "Raspberry Pi Foundation" | awk '{print $1;}')

# Set up acces using ssh key
# ssh-copy-id $RASPBERRY_USER@$RASPBERRY_IP

# Raspberry Pi: ssh connection
ssh $RASPBERRY_USER@$RASPBERRY_IP
