#!/bin/bash

# Tech With Tim (How To Deploy A React-App - Using NGINX & Linux)

URL=rgdlr.sytes.net

echo "Building app"
npm run build

echo "Deploying files to server"
scp -r build/* pi@$URL:/var/www/$URL
