#!/bin/bash

# Install firewall
sudo apt install ufw -y

# Update iptables
# update-alternatives --list iptables
# sudo update-alternatives --set iptables /usr/sbin/iptables-legacy

# Update kernel
# sudo raspi-update

# Limit ssh connections through firewall
sudo ufw limit 22
sudo ufw limit 80
sudo ufw limit 443
sudo ufw enable
