#!/bin/bash

# Raspberry Pi: default user and password
RASPBERRY_USER=pi
RASPBERRY_PASSWORD=raspberry

# Raspberry Pi: IP address
RASPBERRY_IP=$(sudo arp-scan -l | grep "Raspberry Pi Foundation" | awk '{print $1;}')

# Prompt
# echo "$RASPBERRY_USER@$RASPBERRY_IP's password: $RASPBERRY_PASSWORD"

# Hosts
# echo -e "$RASPBERRY_IP\traspberry" | sudo tee -a /etc/hosts


# Raspberry Pi: ssh connection
ssh $RASPBERRY_USER@$RASPBERRY_IP
