#!/bin/bash

URL=rgdlr.sytes.net

# Install nginx
sudo apt-get install nginx -y

# Create folder for nginx source code
sudo mkdir /var/www/$URL
sudo chmod 755 -R /var/www/$URL
sudo chown -R $(whoami):www-data /var/www/$URL

# Configure server site (later modified by certbot ssl)
echo "server {
	listen 80;
	listen [::]:80;

	server_name  www.$URL;

	root /var/www/$URL;
	index index.html;

	location / {
		try_files $uri $uri/ =404;
	}
}" | sudo tee -a /etc/nginx/sites-available/$URL


# Test configuration
sudo nginx -t

# Set configuration as default
sudo unlink /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/$URL /etc/nginx/sites-enabled

# Restart nginx
sudo systemctl restart nginx
