#!/bin/bash

# Install firewall
echo " ⏳ Firewall install"
sudo apt-get install ufw -y 1> /dev/null
echo -ne "\e[1A\e[K"
echo " ✅ Firewall install"

# Update iptables
# update-alternatives --list iptables
# sudo update-alternatives --set iptables /usr/sbin/iptables-legacy

# Update kernel
# sudo raspi-update

# Limit ssh connections through firewall
echo " ⏳ Firewall configuration"
sudo ufw limit 22 1> /dev/null
sudo ufw limit 80 1> /dev/null
sudo ufw limit 443 1> /dev/null
sudo ufw limit 22022 1> /dev/null
sudo ufw limit 44380 1> /dev/null
sudo ufw enable 1> /dev/null
echo -ne "\e[1A\e[K"
echo " ✅ Firewall configuration"

# Show ufw status
# sudo ufw status
